#-------------------------------
# General Site Settings
title: Facts First
logo: logo.png # You can add own logo.
description: Facts First is an organization dedicated to teaching people to think for themselves and fight misinformation and logical fallicies


#-------------------------------
# Author Settings
author:
  name: Facts First
  image: logo.png
  say-hello:  , this is <strong>Facts First</strong>
  bio: an orginization dedicated to teaching teenagers to think for themsevles and fight misinformation and logcial fallicies on social media platforms


#-------------------------------
# Contact links
#twitter: https://twitter.com/ # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://www.instagram.com/facts__first/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: facts__first # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e